name: "FlashForge"
description: "Monitor your Flashforge Finder via API"
version: "0.0.1"
slug: "flashforge"
stage: experimental
startup: services
log_level: info
boot: auto
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  Port: 8899
  Local_Only: false
schema:
  Port: int
  Local_Only: bool