name: "I2C OLED Display"
description: "This addon lets you display to your I2C OLED for a Raspberry Pi with an I2C SSD1306 0.91\" 128x32 OLED."
version: "1.0.2"
slug: "i2c_oled_display"
startup: services
boot: manual
hassio_api: true
init: false
ingress: true
auth_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - media:rw
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-2
  - /dev/i2c-3
  - /dev/i2c-4
  - /dev/i2c-5
  - /dev/i2c-6
  - /dev/i2c-7
  - /dev/i2c-8
  - /dev/i2c-9
  - /dev/i2c-10
  - /dev/i2c-11
  - /dev/i2c-12
  - /dev/i2c-13
  - /dev/i2c-14
  - /dev/i2c-15
  - /dev/i2c-16
  - /dev/i2c-17
  - /dev/i2c-18
  - /dev/i2c-19
  - /dev/i2c-20
options:
  Default_Duration: 10
  I2C_bus: 1
  Screenshot: ''

  Debug_Mode: false

  DateTime_Format: "%d/%m/%Y %H:%M:%S"
  Graceful_Exit_Text: "Exited at {datetime}"

  Show_Static_Screen: true
  Static_Screen_Text: "Hassio verion {hassio.os.version} on {hostname} with IP {ip}"
  Static_Screen_Text_NoScroll: false
  Static_Screen_Text_Animated_Wave: 8

  Show_Welcome_Screen: true
  Welcome_Screen_Duration: 5
  Welcome_Screen_Limit: 2
  Welcome_Screen_Text: "Welcome to {hostname}"

  Show_Splash_Screen: true
  Splash_Screen_Duration: 5
  Splash_Screen_Limit: 0

  Show_Network_Screen: true
  Network_Screen_Duration: 10
  Network_Screen_Limit: 0

  Show_CPU_Screen: true
  Temperature_Unit: "C"
  CPU_Screen_Duration: 5
  CPU_Screen_Limit: 0

  Show_Memory_Screen: true
  Memory_Screen_Duration: 5
  Memory_Screen_Limit: 0

  Show_Storage_Screen: true
  Storage_Screen_Duration: 5
  Storage_Screen_Limit: 0

schema:
  I2C_bus: "int(0,20)"
  Default_Duration: int
  Screenshot: "list(|/media)"
  Debug_Mode: bool
  DateTime_Format: "string?"
  Graceful_Exit_Text: "string?"

  Show_Static_Screen: bool
  Static_Screen_Text: "string?"
  Static_Screen_Text_NoScroll: bool
  Static_Screen_Text_Animated_Wave: "int?"

  Show_Welcome_Screen: bool
  Welcome_Screen_Text: "string?"
  Welcome_Screen_Duration: "int?"
  Welcome_Screen_Limit: "int?"

  Show_Splash_Screen: bool
  Splash_Screen_Duration: "int?"
  Splash_Screen_Limit: "int?"

  Show_Network_Screen: bool
  Network_Screen_Duration: "int?"
  Network_Screen_Limit: "int?"

  Show_CPU_Screen: bool
  Temperature_Unit: "list(C|F)?"
  CPU_Screen_Duration: "int?"
  CPU_Screen_Limit: "int?"

  Show_Memory_Screen: bool
  Memory_Screen_Duration: "int?"
  Memory_Screen_Limit: "int?"

  Show_Storage_Screen: bool
  Storage_Screen_Duration: "int?"
  Storage_Screen_Limit: "int?"